### ISSUE TITLE
Game randomly freezes in midgame

### ISSUE THREAD

**Issue by ghost** [Mic238/osu-for-Mac-Stable-Latest#18]
When in game, the game randomly freezes for few second, with sound still going on but nothing on screen moving. The game itself should also be freezing as no "miss" sound was played when the game freeze. In that few second, no input is detected and the screen just stopped. 

** This might be due to the low spec of my device but may also be an issue with the wine framework?

Problem happened on Macbook AIr (2014) running macOS Mojave 10.14.3 (18D109) with latest version of Osu. (Additional info: Tablet input driver is depreciated from Wacom, don't know if that have an affect on the problem)

**Comment by Mic238** [comment]
It's a common but random problem I should say. It happens to myself as well but as the chance is so rare, I just can't see where the problem is and decide to leave it as it is. 

I believe It's not related to the spec, as osu doesn't require high spec even for 240 FPS and apparently wine only use a single core to run. It might be wine framework but obviously there's nothing I can do with it.

Lazer should be live pretty soon and that will be a native universal app, so I suppose it will run a lot better.

**Comment by ghost** [comment]
I was about to add some more info on the problem as I later found that replaying gameplay can also reproduce the freeze. It should be the beatmap rendering part that froze. And yes, I am looking forward for lazer too :D.

Thank you for the reply.
