### ISSUE TITLE
Problems with the fonts

### ISSUE THREAD

**Issue by Zeekk9** [Mic238/osu-for-Mac-Stable-Latest#5]
In some places, the font is not visible, for example in the settings and the headers, any solution?
Thanks for the support!

**Comment by Mic238** [comment]
Hi there, this problem is now fixed (finally!). Please redownload the package to follow update procedure.
Just a reminder if you have installed 2018-001 Security Update, it will not run for some reason, which there is nothing I can do at the moment.
But unfortunately, gpiplus (which is used to render those missing icons) is incompatible with cjkfonts, which means those characters would appear as boxes
