### ISSUE TITLE
After installed, it's always downloading

### ISSUE THREAD

**Issue by lwenn** [Mic238/osu-for-Mac-Stable-Latest#7]
![image](https://user-images.githubusercontent.com/4468391/35843568-e2734464-0b43-11e8-9658-779fd3b5e308.png)
As the picture, how to deal it? Can I play the game? My OS is 10.11.6.

**Comment by Evyde** [comment]
# Same Problem
My macOS version is 10.13.3.
And before it starts, wine announces that
![Wine](http://7xju1y.com1.z0.glb.clouddn.com/20180213161837_eDaPTj_%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-02-13%20%E4%B8%8B%E5%8D%884.18.31.png)

**Comment by Mic238** [comment]
The problem seems to be osu itself that couldn't download discord-rpc.dll.

I just uploaded a copy of this file to the root as well as in the dedicate folder so it shouldn't be anymore issue with this.

Simply download the discord-rpc.dll file and move it in /Applications/osu!.app/drive_c/Program Files/osu (where you can find you boatman folder), or if you like, redownload the whole client

Thanks for letting me know and sorry for the late reply.

@ForeverOpp This can be ignored and it shouldn't bring any issue with game play
